#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Dec  9 21:10:51 2021

@author: chaitanyasudarsan
"""
Distance = float(input("Distance:"))
unit= input("'K'ilometer or 'M'iles :")
if unit.upper() == "K":
    converted = Distance / 1.609344
    print("Distance in miles is" + str(converted))
    
else:
    converted = Distance * 1.609344
    print("Distance in Kilometers is " + str(converted))
    
