#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Dec 12 17:06:19 2021

@author: chaitanyasudarsan
"""
import random
def play():
    user = input("whats your choice? ""'r'for rock; 'p' for papaer; 's' for scissors")
    computer = random.choice(['r','p','s'])
    if user == computer:
        return('Its\ a tie')
    if is_win(user ,computer):
        return'You Won'
        
    return'You lost'

  
    #r > s , s > p , p >r
def is_win (player,opponent):
    # return true if player wins
    if (player == 'r' and opponent == 's') or \
        (player == 's' and opponent == 'p') or \
            (player == 'p' and opponent == 'r'):
        return True
        
print(play())              